### PR TITLE
Improve step 6

### PR DESCRIPTION
**Pull request by jmartisk**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@jmartisk thanks a lot!

Random idea: since we already use a "database" (imitated though) with customers and bookings, we could actually create a real database and have another chatbot/agent, but for internal use of employees. Then we could demonstrate the use of `SqlDatabaseContentRetriever` (e.g. "what is the average rental period by month/location", "give me our top 10 frequent customers", etc.). WDYT?

**Comment by jmartisk** [comment]
That's not a bad idea! Step 7 could be maybe turned into this, because I don't see a useful case for reranking in the current workshop. I'll submit an issue

**Comment by langchain4j** [comment]
@jmartisk reranking can still be demonstrated if we add more policies/documentation

**Comment by jmartisk** [comment]
@langchain4j my understanding is that reranking is generally useful for hybrid queries from different sources (which have mutually incomparable scoring strategies), but if you just use a single embedding store, then scores from a good embedding model should usually be enough for ranking the search results, no? Or at least I find it hard to explain why you should use a scoring model after you have already scored the results by computing the vector distance.

**Comment by langchain4j** [comment]
@jmartisk, reranking is still benefitial even if you have a single source/store.

The idea is to optimize retrieval by having 2-stages:
- on the first stage a faster/cheaper (but worse) model is used to retrieve (let's say 1000) most relevant documents (from let's say 1.000.000)
- on the second stage a slower/expensiver (but much better) model is used to filter retrieved documents even further (let's say down to 20)

Reranking/scoring models have a different (as compared to embedding models) network architecture/structure, so they can perform better (but much slower).

**Pull request merged**
